package com.db.model;

public class Nutritioninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.nrvvalue
     *
     * @mbggenerated
     */
    private String nrvvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.measurement
     *
     * @mbggenerated
     */
    private String measurement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.rounding
     *
     * @mbggenerated
     */
    private String rounding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.contrastmark
     *
     * @mbggenerated
     */
    private String contrastmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.criticalvalue
     *
     * @mbggenerated
     */
    private String criticalvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nutritioninfo.energyrate
     *
     * @mbggenerated
     */
    private String energyrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.id
     *
     * @return the value of nutritioninfo.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.id
     *
     * @param id the value for nutritioninfo.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.name
     *
     * @return the value of nutritioninfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.name
     *
     * @param name the value for nutritioninfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.nrvvalue
     *
     * @return the value of nutritioninfo.nrvvalue
     *
     * @mbggenerated
     */
    public String getNrvvalue() {
        return nrvvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.nrvvalue
     *
     * @param nrvvalue the value for nutritioninfo.nrvvalue
     *
     * @mbggenerated
     */
    public void setNrvvalue(String nrvvalue) {
        this.nrvvalue = nrvvalue == null ? null : nrvvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.measurement
     *
     * @return the value of nutritioninfo.measurement
     *
     * @mbggenerated
     */
    public String getMeasurement() {
        return measurement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.measurement
     *
     * @param measurement the value for nutritioninfo.measurement
     *
     * @mbggenerated
     */
    public void setMeasurement(String measurement) {
        this.measurement = measurement == null ? null : measurement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.rounding
     *
     * @return the value of nutritioninfo.rounding
     *
     * @mbggenerated
     */
    public String getRounding() {
        return rounding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.rounding
     *
     * @param rounding the value for nutritioninfo.rounding
     *
     * @mbggenerated
     */
    public void setRounding(String rounding) {
        this.rounding = rounding == null ? null : rounding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.contrastmark
     *
     * @return the value of nutritioninfo.contrastmark
     *
     * @mbggenerated
     */
    public String getContrastmark() {
        return contrastmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.contrastmark
     *
     * @param contrastmark the value for nutritioninfo.contrastmark
     *
     * @mbggenerated
     */
    public void setContrastmark(String contrastmark) {
        this.contrastmark = contrastmark == null ? null : contrastmark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.criticalvalue
     *
     * @return the value of nutritioninfo.criticalvalue
     *
     * @mbggenerated
     */
    public String getCriticalvalue() {
        return criticalvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.criticalvalue
     *
     * @param criticalvalue the value for nutritioninfo.criticalvalue
     *
     * @mbggenerated
     */
    public void setCriticalvalue(String criticalvalue) {
        this.criticalvalue = criticalvalue == null ? null : criticalvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nutritioninfo.energyrate
     *
     * @return the value of nutritioninfo.energyrate
     *
     * @mbggenerated
     */
    public String getEnergyrate() {
        return energyrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nutritioninfo.energyrate
     *
     * @param energyrate the value for nutritioninfo.energyrate
     *
     * @mbggenerated
     */
    public void setEnergyrate(String energyrate) {
        this.energyrate = energyrate == null ? null : energyrate.trim();
    }
}