package com.db.model;

public class testPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.colum1
     *
     * @mbggenerated
     */
    private String colum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.column2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.colum1
     *
     * @return the value of test.colum1
     *
     * @mbggenerated
     */
    public String getColum1() {
        return colum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.colum1
     *
     * @param colum1 the value for test.colum1
     *
     * @mbggenerated
     */
    public void setColum1(String colum1) {
        this.colum1 = colum1 == null ? null : colum1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.column2
     *
     * @return the value of test.column2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.column2
     *
     * @param column2 the value for test.column2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }
}