package com.db.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.emailaddr
     *
     * @mbggenerated
     */
    private String emailaddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.userid
     *
     * @return the value of sysuser.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.userid
     *
     * @param userid the value for sysuser.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.username
     *
     * @return the value of sysuser.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.username
     *
     * @param username the value for sysuser.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.password
     *
     * @return the value of sysuser.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.password
     *
     * @param password the value for sysuser.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.phonenum
     *
     * @return the value of sysuser.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.phonenum
     *
     * @param phonenum the value for sysuser.phonenum
     *
     * @mbggenerated
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.emailaddr
     *
     * @return the value of sysuser.emailaddr
     *
     * @mbggenerated
     */
    public String getEmailaddr() {
        return emailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.emailaddr
     *
     * @param emailaddr the value for sysuser.emailaddr
     *
     * @mbggenerated
     */
    public void setEmailaddr(String emailaddr) {
        this.emailaddr = emailaddr == null ? null : emailaddr.trim();
    }
}